website/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^(?P<type_>[a-zA-Z-]+)/$', views.base_form, name='form'),
    url(r'^(?P<type_>[a-zA-Z-]+)/(?P<code>\w{25})/$', views.form_confirm, name='form_confirm'),
    url(r'^(?P<type_>[a-zA-Z-]+)/txt/(?P<d_link>\w{20})/$', views.txt_download, name='txt_download')
]

website/base/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from base import views


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

website/templates/includes/_footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <a href="{% url 'index' %}"> Accounts</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

website/templates/includes/_header.html


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:main' %}">Accounts</a>
      </li>
    </ul>
  </div>
</nav>