website/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^(?P<type_>[a-zA-Z-]+)/$', views.base_form, name='form'),
    url(r'^(?P<type_>[a-zA-Z-]+)/(?P<code>\w{25})/$', views.form_confirm, name='form_confirm'),
    url(r'^(?P<type_>[a-zA-Z-]+)/txt/(?P<d_link>\w{20})/$', views.txt_download, name='txt_download')
]

website/base/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
]

website/website/urls.py
from django.contrib import admin
from django.conf.urls import url, include

from base import views


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

website/accounts/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from decimal import Decimal

# Create your models here.


class Group(models.Model):
    title = models.CharField(max_length=20)

    class Meta:
        verbose_name = 'Група'
        verbose_name_plural = 'Групы'

    def __str__(self):
        return self.title


class Coupon(models.Model):
    code = models.CharField(max_length=50, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField()

    class Meta:
        verbose_name = 'Купон'
        verbose_name_plural = 'Купоны'

    def __str__(self):
        return self.code


class AccountType(models.Model):
    group = models.ForeignKey('Group', on_delete=models.CASCADE, null=True, blank=True, default=None)
    name = models.CharField('Категория', max_length=30)
    description = models.CharField('Описание', max_length=200)
    price = models.DecimalField('За 1 шт.', decimal_places=2, max_digits=7, default=0)

    def get_short_description(self):
        if len(self.description) > 50:
            return '%s..' % self.description[:50]
        return self.description

    def get_count(self):
        return Account.objects.filter(type=self, is_active=True).count()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория аккаунта'
        verbose_name_plural = 'Категории аккаунтов'


class Order(models.Model):
    METHOD_CHOICE = (
        ('QIWI', 'Qiwi'),
    )
    type = models.ForeignKey('AccountType', on_delete=models.CASCADE)
    payment_method = models.CharField('Способ оплаты', max_length=10, choices=METHOD_CHOICE, default='QIWI')
    count = models.PositiveIntegerField('Кол-во', validators=[MinValueValidator(1)])
    pay_comment = models.CharField('Qiwi примечание', max_length=20)
    paid = models.BooleanField('Оплачен', default=False)
    complete = models.BooleanField('Аккаунты выданы', default=False)
    email = models.EmailField(default=None)
    total_price = models.DecimalField(decimal_places=2, max_digits=7, default=0)
    download_code = models.CharField(max_length=30, default=None, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', related_name='orders', null=True, blank=True, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def save(self, *args, **kwargs):
        self.total_price = self.count * self.type.price
        if self.coupon and self.coupon.active:
            self.total_price = self.total_price - self.total_price * (self.coupon.discount / Decimal('100'))
        super(Order, self).save(*args, **kwargs)

    def __str__(self):
        return self.created.strftime("%A, %d. %B %Y %I:%M%p")


class Account(models.Model):
    type = models.ForeignKey('AccountType', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, default=None, null=True, blank=True)
    login = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    is_active = models.BooleanField(default=True)  # Еще не продан - True

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'

    def __str__(self):
        return self.login

website/accounts/forms.py
from django import forms
from .models import Order


class OrderForm(forms.ModelForm):
    code = forms.CharField(max_length=20, required=False, label='Код купона',
                           widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Order
        fields = ['count', 'email', 'payment_method']
        widgets = {
            'count': forms.TextInput(attrs={'class': 'form-control',
                                            'type': 'number',
                                            'min': '1',
                                            'value': '1'}),
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'payment_method': forms.Select(attrs={'class': 'custom-select mb-2 mr-sm-2 mb-sm-0'})
        }

website/accounts/views.py
import string

from django.shortcuts import (
    render,
    get_object_or_404,
    redirect
)
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponse, Http404
from django.db import transaction, IntegrityError

from .models import AccountType, Order, Account, Group, Coupon
from .forms import OrderForm
from .funcs import generator, CountException, check_status
from website import settings

from collections import namedtuple


def main(request):
    groups = Group.objects.all()
    s = namedtuple('Section', 'title accounts')
    groups_s = [s(g.title, AccountType.objects.filter(group=g)) for g in groups]

    return render(request, 'main.html', {'groups': groups_s})


def base_form(request, type_):
    form = OrderForm(request.POST or None)

    try:
        del request.session['id']
    except KeyError:
        pass

    if form.is_valid():
        try:
            data = form.cleaned_data
            if data['count'] > AccountType.objects.get(name=type_).get_count():
                raise CountException

            try:
                coupon = Coupon.objects.get(code=data['code'])
            except Coupon.DoesNotExist:
                coupon = None

            order = Order(email=data['email'],
                          coupon=coupon,
                          count=data['count'],
                          payment_method=data['payment_method'],
                          type=get_object_or_404(AccountType, name=type_))

            order.pay_comment = generator(size=8, chars=string.digits)
            order.save()
            request.session['id'] = order.id

            return redirect(reverse('accounts:form_confirm', args=[type_, generator(size=25)]))
        except CountException:
            messages.add_message(request, messages.INFO, 'Недостаточно аккаунтов.')

    return render(request, 'form.html', {'type': type_,
                                         'form': form})


def form_confirm(request, type_, code):
    order = get_object_or_404(Order, pk=request.session.get('id', None))

    if request.POST:
        # TODO: Delete after, temp check
        if check_status(order):  # Проверка оплаты
            order.paid = True
            order.download_code = generator(size=20)
            order.save()

    qiwi_link = 'https://qiwi.com/payment/form/99?amountFraction=0&currency=RUB&extra%5B%27account%27%5D={}' \
                '&extra%5B%27comment%27%5D={}&amountInteger={}'.format(settings.base_num,
                                                                       order.pay_comment,
                                                                       order.total_price)
    return render(request, 'form_confirm.html', {'order': order,
                                                 'number': settings.base_num,
                                                 'qiwi_link': qiwi_link})


def txt_download(request, type_, d_link):
    local_type = AccountType.objects.get(name=type_)
    order = get_object_or_404(Order, pk=request.session.get('id', None))

    if d_link == order.download_code and local_type.get_count() > order.count:
        accounts = []
        if order.complete:
            accs = Account.objects.filter(order=order)
            accounts = ['%s:%s' % (a.login, a.password) for a in accs]
        else:
            for a in Account.objects.filter(type=local_type, is_active=True)[:order.count]:
                try:
                    with transaction.atomic():
                        a.order = order
                        a.is_active = False
                        a.save()
                        accounts += ['%s:%s' % (a.login, a.password)]
                except IntegrityError:
                    raise Http404('Ошибка во время запроса, свяжитесь с администрацией.')

            order.complete = True
            order.save()

        filename = 'accounts_{}.txt'.format(generator(size=15))
        content = '\r\n'.join(accounts)
        response = HttpResponse(content, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename={0}'.format(filename)
        return response
    else:
        raise Http404('Неверный адрес или недостаточно аккаунтов')

website/accounts/templates/form.html
{%  extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    <h3>{{ type }}</h3>
    <div class="row">
        <div class="col-md-4">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Отправить" class="btn btn-primary">
        </form>
        </div>
    </div>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

website/accounts/templates/form_confirm.html
{% extends 'base.html' %}

{% block title %}

{% endblock %}

{% block content %}
    {% if order %}
        <div class="col-md-6">
            {% if order.coupon %}
                <h5>Купон на скидку {{ order.coupon.discount }}%</h5>
            {% else %}
                <h5>Купон не использован</h5>
            {% endif %}
            <table class="table">
                <tbody>
                    <tr>
                        <th>Товар</th>
                        <td>{{ order.type.name }}</td>
                    </tr>
                    <tr>
                        <th>Кол-во</th>
                        <td>{{ order.count }}</td>
                    </tr>
                    <tr>
                        <th>К оплате</th>
                        <td>{{ order.total_price }}р.</td>
                    </tr>
                    <tr>
                        <th>Кошелек</th>
                        <td>{{ number }}</td>
                    </tr>
                    <tr>
                        <th>Примечание</th>
                        <td>{{ order.pay_comment }}</td>
                    </tr>
                </tbody>
            </table>

            {% if not order.paid %}
            <a href="{{ qiwi_link }}" target="_blank">Оплатить</a>
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Проверить" class="btn btn-primary">
            </form>
            {% endif %}

            {% if order.paid %}
                <p>Оплачено</p>
                <a href="{% url 'accounts:txt_download' order.type.name order.download_code %}">Ссылка для скачивания.</a>
            {% else %}
                <p>Не оплачено</p>
            {% endif %}

            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    {% endif %}
{% endblock %}

website/accounts/templates/main.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}Accounts{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'accounts/css/main.css' %}">
{% endblock %}

{% block content %}

<h1>Магазин аккаунтов.</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
    Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
    Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
    Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Описание</th>
          <th scope="col">Кол-во</th>
          <th scope="col">За 1 шт.</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% if groups %}
        {% for g in groups %}
            <tr style="background-color: lightgray; text-align: center"><td colspan="10">{{ g.title }}</td></tr>
            {% for acc in g.accounts %}
            <tr>
              <td>{{ acc.name }}, {{ acc.get_short_description }}</td>
              <td>{{ acc.get_count }}</td>
              <td>{{ acc.price }}р.</td>
              <td><a href="{% url 'accounts:form' acc.name %}">Купить</a></td>
            </tr>
            {% endfor %}
        {% endfor %}
        {% endif %}
      </tbody>
    </table>



{%  endblock %}